---
- name: SSL certificate files are installed
  copy: src="{{ django_hostname }}.{{ item }}" dest="/etc/ssl/private/{{ django_hostname }}.{{ item }}"
  with_items: ['cert', 'key']
  notify:
    - reload nginx conf
  tags: ['certs']

- name: Disable deafult site if variable set
  shell: /usr/bin/nginx_dissite default
  when: django_set_as_default_http_in_nginx

- name: Nginx config files are installed
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: nginx-site.jinja2, dest: "/etc/nginx/sites-available/{{ django_hostname }}" }
    - { src: nginx-maint-site.jinja2, dest: "/etc/nginx/sites-available/{{ django_hostname }}-maint" }
  register: nginx_conf

- name: Check nginx configuration file
  shell: nginx -t
  when: nginx_conf.changed

- name: Enable nginx normal site
  shell: /usr/bin/nginx_ensite {{ django_hostname }}
  when: nginx_conf.changed

- name: Disable nginx maint site
  shell: /usr/bin/nginx_dissite {{ django_hostname }}-maint
  register: nginx_config_maint_site
  ignore_errors: yes
  when: nginx_conf.changed

- name: reload nginx conf
  service: name=nginx state=reloaded
  when: nginx_conf.changed

